# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: first_finger
  joint_model_group_pose: first_pose
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - base_to_first_finger_01
    - first_finger_01_to_02
    - first_finger_02_to_03
    - base_to_fourth_finger_01
    - fourth_finger_01_to_02
    - fourth_finger_02_to_03
    - base_to_second_finger_01
    - second_finger_01_to_02
    - second_finger_02_to_03
    - base_to_third_finger_01
    - third_finger_01_to_02
    - third_finger_02_to_03
    - base_to_thumb_01
    - thumb_01_to_02
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
position_controller:
  type: position_controllers/JointPositionController
  joints:
    - base_to_first_finger_01
    - first_finger_01_to_02
    - first_finger_02_to_03
    - base_to_second_finger_01
    - second_finger_01_to_02
    - second_finger_02_to_03
    - base_to_fourth_finger_01
    - fourth_finger_01_to_02
    - fourth_finger_02_to_03
    - base_to_thumb_01
    - thumb_01_to_02
    - base_to_third_finger_01
    - third_finger_01_to_02
    - third_finger_02_to_03
  gains:
    base_to_first_finger_01:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    first_finger_01_to_02:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    first_finger_02_to_03:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    base_to_second_finger_01:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    second_finger_01_to_02:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    second_finger_02_to_03:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    base_to_fourth_finger_01:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    fourth_finger_01_to_02:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    fourth_finger_02_to_03:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    base_to_thumb_01:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    thumb_01_to_02:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    base_to_third_finger_01:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    third_finger_01_to_02:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    third_finger_02_to_03:
      p: 100
      d: 1
      i: 1
      i_clamp: 1